### ISSUE TITLE
Documentation for using wp-now with Playground

### ISSUE THREAD

**Issue by flexseth** [adamziel/playground-docs-workflow#31]
## Error code
```SHELL 
command not found: wp-now
```

## Exists when
User has not installed `wp-now` package
https://www.npmjs.com/package/@wp-now/wp-now

If `wp-now` is not installed on a users machine, many of the commands will not work.

## The need
Blueprints or instructions that use the `wp-now` package should help users navigate how to install and use the package with Playground.

## Docs to include
- Requirements & known limitations
- `wp-now` vs. VS Code extension
- Installing via `npx`
- Installing in a single directory vs. globally on your machine
- Using blueprints with `wp-now` 
- etc

**Comment by ironnysh** [comment]
That's already available on [NPM](https://www.npmjs.com/package/@wp-now/wp-now)/[GitHub](https://github.com/WordPress/playground-tools/tree/trunk/packages/wp-now), so just need to import the [README](https://github.com/WordPress/playground-tools/blob/trunk/packages/wp-now/README.md) to the docs directory. Or am I missing something? :-)

And slightly off-topic: [the image in the README](https://github.com/WordPress/playground-tools/blob/1d68c64ece37123931d3bef9acca9d38af448d66/packages/wp-now/README.md?plain=1#L54) is broken on NPM.

**Comment by adamziel** [comment]
> That's already available on [NPM](https://www.npmjs.com/package/@wp-now/wp-now)/[GitHub](https://github.com/WordPress/playground-tools/tree/trunk/packages/wp-now), so just need to import the [README](https://github.com/WordPress/playground-tools/blob/trunk/packages/wp-now/README.md) to the docs directory. Or am I missing something? :-)

You're exactly right! :-)

**Comment by ironnysh** [comment]
Coolio. Will do it tomorrow :-)

**Comment by flexseth** [comment]
## About `wp-now`
> wp-now streamlines the process of setting up a local WordPress environment.
See the NPM package on [wp-now](https://www.npmjs.com/package/@wp-now/wp-now).

## Requirements
`wp-now` includes an entire WordPress environment, so you don't need to install WordPress separately. It runs on PHP WASM (Web Assembly) - **@ironnysh** - please provide link for more context

`Node.js` is required to run `wp-now`. You can download it from the [Node.js website](https://nodejs.org/).
Node is required because the Playground using NPM behind the scenes to install packages.

---

## Boot modes
`theme`
`plugin`
`wp-content`
"blueprint mode" - on the roadmap
(@ironnysh - I've documented `wp-content` mode here a little bit)

## Limitations
When booting in `wp-content` mode without a theme, you will receive an error that there is no theme present.
Solution: Add an empty `themes` directory 

## `shell` step in `wp-now` with `wp-cli`
The `shell` step currently won't work in `wp-now` because it doesn't support the `shell` command.
This is a known limitation that we are working towards making work! 

## Other known limitations

Please check the Playground Tools GitHub repo for [issues related to](https://github.com/search?q=repo%3AWordPress%2Fwordpress-playground+wp-now&type=issues) `wp-now` 

Also see the [Known Limitations](https://www.npmjs.com/package/@wp-now/wp-now#known-issues) sections on the `wp-now` documentation for more info

---

## How to boot up Playground in easy mode
`wp-content` mode 
- Loads up everything in the `wp-content` directory
- Themes, Plugins, and Uploads

A great option if you want to create a new theme for a website, or work with existing website content.
TODO: Show steps to boot in `wp-content` mode - @ironnysh :) 

Or want to work with an existing website to test out a plugin or theme.

### How to boot up Playground in `wp-content` mode
Content needed for `wp-content` mode
WordPress installation should include the following:
- All uploaded media to this website
- The current theme being used
- All plugins being used

---

## Security warnings
Sometimes when you use `NPM` packages from an external source, the project you are using needs to update them. 

See the [Security Warnings](./playground-tools/wp-now/fixing-security-warnings.md) page for more information on how to audit and fix security issues in `wp-now`.

You can report these types of errors if you aren't able to get them fixed.
Here is a sample error report on the `playground-tools` repo
- [wp-now: Resolve npm audit warnings #224](https://github.com/WordPress/playground-tools/issues/224)
- [ ] TODO: Update docs with how to audit and fix security issues in `wp-now`


> wp-now: Error starting: getaddrinfo ENOTFOUND
- https://github.com/adamziel/playground-docs-workflow/issues/32

**Comment by flexseth** [comment]
@ironnysh Included a bunch of notes. They're kinda organized. :)

**Comment by ironnysh** [comment]
@flexseth, thanks for the list :-)

I went over everything here, as well as the published docs (specifically, [the Contributing chapter](https://wordpress.github.io/wordpress-playground/contributing/index)), and I have some suggestions.

If it’s okay with you (and @adamziel, of course :-) ), I’d like to propose this as a working plan, which I’d be happy to take on.

## Reorganize the chapters
1. Add a new chapter: Local Playground, which will include:
   * The `wp-now` README (**_note:_** the [`wp-now` docs](https://github.com/WordPress/playground-tools/blob/trunk/packages/wp-now/README.md) are outdated, and need to be revised before importing to Docusaurus. See details below, under "`wp-now` Docs").
   * The VS Code extension [doc](https://github.com/WordPress/playground-tools/blob/trunk/packages/vscode-extension/README.md).
   * Restructure the current [Usage in Node.js](https://wordpress.github.io/wordpress-playground/usage-in-node-js) chapter into a page, focusing only on the [@php-wasm/node package](https://npmjs.org/@php-wasm/node) (i.e., import the README to the docs).

* The [FAQ](https://wordpress.github.io/wordpress-playground/faq) should be removed
* The [WordCamp Contributor Day](https://wordpress.github.io/wordpress-playground/wordcamp-contributor-day) needs a rewrite, and should be under the Contributing chapter.

## Revise the Contributing chapter
All the subsections in the Contributing chapter need a rewrite.
* [The NX chapter](https://wordpress.github.io/wordpress-playground/contributing/packages-and-projects): remove all general NX text (no reason to recreate the NX docs) and migrate only what’s relevant to Playground to the [Code contribution page](https://wordpress.github.io/wordpress-playground/contributing/code). NX is also mentioned under [Architecture Overview](https://wordpress.github.io/wordpress-playground/architecture/index/), so that’s covered.
* The Code Contributions page mentions [needing local custom domains](https://wordpress.github.io/wordpress-playground/contributing/code#https-setup). Is it still required or was it resolved [since the original PR](https://github.com/WordPress/wordpress-playground/pull/888)? The [local debug](https://wordpress.github.io/wordpress-playground/contributing/code#debugging-with-vscode-and-chrome) is Windows-only, and should mention you need Chrome installed ;-) 
* The [Coding standards](https://wordpress.github.io/wordpress-playground/contributing/coding-standards) page should be renamed, shortened, and integrated at the top of the Code Contributions page.
* The [Triage Contributions](https://wordpress.github.io/wordpress-playground/contributing/triage) page feels out of place. It should be summarized and added to the [Start Contributing](https://wordpress.github.io/wordpress-playground/contributing/index) page.
* The [Publishing Packages, Releases, and More](https://wordpress.github.io/wordpress-playground/contributing/publishing) chapter should be removed. The relevant sections should be moved under [Architecture Overview](https://wordpress.github.io/wordpress-playground/architecture/index/) 
* The [Crash Reports](https://wordpress.github.io/wordpress-playground/contributing/crash-reports) page should be shortened, and either moved under [Architecture Overview](https://wordpress.github.io/wordpress-playground/architecture/index/) or the  [Code contribution page](https://wordpress.github.io/wordpress-playground/contributing/code).
* The [Contributing Documentation](https://wordpress.github.io/wordpress-playground/contributing/documentation) page: I suggest adding `"dev:docs": "nx dev docs-site",` to the scripts in Playground’s `package.json`, and rewrite the [A more difficult way with a preview](https://wordpress.github.io/wordpress-playground/contributing/documentation#a-more-difficult-way-with-a-preview) section. Also, the **[documentation tracking issue](https://github.com/WordPress/wordpress-playground/issues/772)** is too long and confusing to serve as a starting point for documentation contributors. There should be a project or a clean, up-to-date issue that’s regularly maintained. Remove the [General guidelines](https://wordpress.github.io/wordpress-playground/contributing/documentation#general-guidelines). 

## `wp-now` Docs

[Using Blueprints](https://www.npmjs.com/package/@wp-now/wp-now#using-blueprints)
1. Let’s add 1-2 simpler Blueprint examples.
2. Shelf the [Defining Custom URLs](https://www.npmjs.com/package/@wp-now/wp-now#defining-custom-urls) until `wp-now` adds support for custom domains or SSL.

[Known issues](https://www.npmjs.com/package/@wp-now/wp-now#known-issues)
Some were resolved for sure. Others, maybe:

* Running wp-now start in 'wp-content' or 'wordpress' mode will produce some empty directories: [WordPress/wordpress-playground\#328](https://github.com/WordPress/wordpress-playground/issues/328) **—Is [this](https://github.com/WordPress/playground-tools/issues/32) still an issue?**

* Inline images are broken when site starts on a different port: [WordPress/wordpress-playground\#356](https://github.com/WordPress/wordpress-playground/issues/356) **—Is [this](https://github.com/WordPress/playground-tools/issues/14) still an issue, given [this](https://github.com/WordPress/wordpress-playground/pull/610) was merged?**

* ~~wp-now doesn't build or start on Windows: [WordPress/playground-tools\#66](https://github.com/WordPress/playground-tools/issues/66), [WordPress/playground-tools\#11](https://github.com/WordPress/playground-tools/issues/11)~~ **RESOLVED**

* ~~It's not possible to set WP_DEBUG and other wp-config.php constants: [WordPress/playground-tools\#17](https://github.com/WordPress/playground-tools/issues/17)~~ **RESOLVED**

* In 'wordpress' mode, wp-now can connect to a MySQL database with define( 'DB_HOST', '127.0.0.1' );, but define( 'DB_HOST', 'localhost' ); does not work: [WordPress/wordpress-playground\#369](https://github.com/WordPress/wordpress-playground/issues/369)

* wp-now published versions can appear random: [WordPress/wordpress-playground\#357](https://github.com/WordPress/wordpress-playground/issues/357) **—Is [this](https://github.com/WordPress/playground-tools/issues/31) still an issue?**


## Misc

- Is it still impossible to run [`wp shell`](https://developer.wordpress.org/cli/commands/shell/) in Playground?
- > See the ~[Security Warnings](https://github.com/adamziel/playground-docs-workflow/issues/playground-tools/wp-now/fixing-security-warnings.md)~ page for more information on how to audit and fix security issues in wp-now.
  
  The link is broken. In any case, if this is related to NPM dependency issues, it shouldn’t be here.
- The [Limitations chapter](https://wordpress.github.io/wordpress-playground/limitations/) needs a rewrite.
- All contribution content should refer also to https://github.com/WordPress/playground-tools/.

**Comment by flexseth** [comment]
> And slightly off-topic: [the image in the README](https://github.com/WordPress/playground-tools/blob/1d68c64ece37123931d3bef9acca9d38af448d66/packages/wp-now/README.md?plain=1#L54) is broken on NPM.

Resolved by
- https://github.com/WordPress/playground-tools/pull/223

**Comment by flexseth** [comment]
@ironnysh - working on some more page updates. 

Also linked an issue that I think could help with organizing some of the content for the pages, once it's all there
- https://github.com/WordPress/wordpress-playground/issues/1269
Been doing some thinking on this, it would be really cool to see a "pricing tables" style view of the features that are

**Comment by flexseth** [comment]
All issues and known limitations of `wp-now` as of the date of this comment 
- https://github.com/flexseth/playground-docs-updates/blob/trunk/wp-now/known-limitations.md

Should take care of that part of the doc update

**Comment by ironnysh** [comment]
> organizing some of the content

@flexseth, are we talking about the documentation site? In any case, [#126](https://github.com/WordPress/wordpress-playground/issues/1269) should probably be a discussion and not an issue.

> issues and known limitations

Probably shouldn't be combined in a single public-facing page in the docs.

Since all the content I mentioned is live, I'd like to work on this “textual refactor” ASAP.
@adamziel, would one PR for all of these be okay with you? I can also separate them by chapters/pages.

**Comment by adamziel** [comment]
@ironnysh That plan looks absolutely amazing! One PR for all of these is amazing, too. Let's make these updates in mdx and Docusaurus at https://github.com/WordPress/wordpress-playground/ as they could already benefit the readers and getting playground-docs-workflow repo ready to use will take a bit more time.

**Comment by ironnysh** [comment]
> Let's make these updates in mdx and Docusaurus at https://github.com/WordPress/wordpress-playground/ 

Right :-) Also adding [Improve the description of SetSiteOptionsStep #1291](https://github.com/WordPress/wordpress-playground/issues/1291) to the list.

**Comment by ironnysh** [comment]
Can close this one 🥳

**Comment by flexseth** [comment]
> Can close this one 🥳

done and done :)
